name: Pull Request Lint Javascript

on:
  pull_request:
    types:
      [
        opened,
        edited,
        reopened,
        synchronize,
        ready_for_review,
        review_requested,
        review_request_removed,
      ]
jobs:
  pull-request-lint-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Get yarn cache directory path
        id: yarn-cache-set-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-set-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        if: steps.yarn-cache-set-path.outputs.cache-hit != 'true'
        run: yarn install
      - name: Lint Package
        run: yarn lint